import { Manrope } from "next/font/google";
import Navbar from "./components/Navbar";
import type { Metadata } from "next";
import "./globals.css";

const manRope = Manrope({
  variable: "--font-manRope",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Relyfe",
  description: "Generated by create next app",
  icons: {
    icon: '/relyfe.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manRope.variable} antialiased bg-[#1E1E1E]`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
